

/**
 *
 * @author Carlos Perez
 */
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Agenda extends javax.swing.JFrame {
    
   public void mostrarContacto(Contacto obcontacto){
        txt_nombre.setText(obcontacto.getNombre());
        txt_apellido.setText(obcontacto.getApellidos());
        txt_telefono.setText(obcontacto.getTelefono());
    }
   
    /**
     * Creates new form Agenda
     */
    private ArrayList <Contacto> ListaContactos = new ArrayList <Contacto>();
    int posicion=-1; 
    int i=-1;
    /*Declaramos un arreylist (arreglo dinamico)
    que va a almacenar objetos 
    se usa la estructura:
    tipo ArrayList tipodato nombrearraylist = new ArrayList tipodato (tamaño);*/
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        guardarRegistro = new javax.swing.JButton();
        btnEliminarContacto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        Q_Peek = new javax.swing.JButton();
        Q_Roll = new javax.swing.JButton();
        Q_Roll1 = new javax.swing.JButton();
        Q_Peek2 = new javax.swing.JButton();
        Btn_Archivar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Telefono");

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        guardarRegistro.setText("Guardar Registro");
        guardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarRegistroActionPerformed(evt);
            }
        });

        btnEliminarContacto.setText("Eliminar Contacto");
        btnEliminarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContactoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        Q_Peek.setText("F Mostrar");
        Q_Peek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_PeekActionPerformed(evt);
            }
        });

        Q_Roll.setText("P Mostrar Eliminar");
        Q_Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_RollActionPerformed(evt);
            }
        });

        Q_Roll1.setText("F Mostrar Eliminar");
        Q_Roll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_Roll1ActionPerformed(evt);
            }
        });

        Q_Peek2.setText("P Mostrar");
        Q_Peek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_Peek2ActionPerformed(evt);
            }
        });

        Btn_Archivar.setText("archivar");
        Btn_Archivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ArchivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAnterior)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(guardarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q_Peek)
                                        .addComponent(btnLimpiar)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnEliminarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Btn_Archivar)
                                .addGap(43, 43, 43)
                                .addComponent(btnModificar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Q_Roll1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(btnPrimero))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSiguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUltimo))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                            .addComponent(txt_apellido))
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q_Peek2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Q_Roll)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimero)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnUltimo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnModificar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Archivar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q_Peek)
                    .addComponent(Q_Roll1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q_Peek2)
                    .addComponent(Q_Roll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // btnUltimo
        //i= ListaContactos.size()-1;
        //mostrarContacto(ListaContactos.get(i-1));
        
        Contacto obcontacto = new Contacto(); /*delcaramos un nuevo objeto de la clase Contacto*/
        int tamano = ListaContactos.size(); /*declaramos una vartiable para almacenar el tamaño del ArrayLIst */
        obcontacto = ListaContactos.get(tamano-1); /*le pasamos al nuevo objeto  el ArrayList con la posicion deseada en este
        caso (tamano-1) para obtener la ltima posicion*/
        txt_nombre.setText(obcontacto.getNombre());/*Le indicamos al campo de texto del form que nos muestre la informacion contenida
        el el objeto "obcontacto" almacenado en la variable nombre.*/
        txt_apellido.setText(obcontacto.getApellidos());
        txt_telefono.setText(obcontacto.getTelefono());
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void guardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarRegistroActionPerformed
         //guardarRegistro
        /* Trabajando con boton Guardar Registro
        declaramos un objeto de la clase que creamos llamada Contacto
        luego llenamos las variables de la clase contacto de la siguiente manera:
        obcontacto.setNombre(txt_nombre.getText());
        aqui estamos utilizando nuestra instancia y luego con el metodo set de la instancia
        le pasamos lo que esta en el TextField por medio del metodo .getText()
        */
        i++;
        Contacto obcontacto = new Contacto(); //instancio el objeto
        obcontacto.setNombre(txt_nombre.getText()); /*lleno la variable nombre del objeto "obcontacto" de la clase Objeto
        por medio del campo de texto "text_nombre" del form por medio del metodo ".getText()"*/
        obcontacto.setApellidos(txt_apellido.getText());
        obcontacto.setTelefono(txt_telefono.getText());
        
        ListaContactos.add(obcontacto); /*Despúes de declarar el Arraylist lo llenamos con el objeto por ser un 
        ArrayList de tipo clases (almacena objetos) 
        Aqui se encuentran almacenadas las tres variables que le definimos al objeto "obcontacto" 
        pero se encuantran como el objetop total*/
        
        JOptionPane.showMessageDialog(rootPane, "Informacion guardada");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_telefono.setText("");
 
    }//GEN-LAST:event_guardarRegistroActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        // btnPrimero
        i=0;
        Contacto obcontacto = new Contacto(); /*delcaramos un nuevo objeto de la clase Contacto*/
        obcontacto = ListaContactos.get(0); /*le pasamos al nuevo objeto  el ArrayList con la posicion deseada*/
        txt_nombre.setText(obcontacto.getNombre());
        /*Le indicamos al campo de texto del form que nos muestre la informacion contenida
        el el objeto "obcontacto" almacenado en la variable nombre.*/
        //txt_apellido.setText(obcontacto.getApellidos());
        //txt_telefono.setText(obcontacto.getTelefono());
        mostrarContacto(ListaContactos.get(i));
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnEliminarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContactoActionPerformed
        // btnEliminar
        Contacto obcontacto = new Contacto();
        obcontacto.getPosicion();       
        //System.out.println("tamano  "+posicion);
        
        
        //obcontacto = ListaContactos.get(posicion);
        txt_nombre.setText(obcontacto.getNombre());
        txt_apellido.setText(obcontacto.getApellidos());
        txt_telefono.setText(obcontacto.getTelefono());
        
                
        ListaContactos.remove(posicion);
        posicion--;
        
        JOptionPane.showMessageDialog(rootPane, "Registro borrado");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_telefono.setText("");
    }//GEN-LAST:event_btnEliminarContactoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // btnAnterior
        //i--;
        //mostrarContacto(ListaContactos.get(i));
        
        Contacto obcontacto = new Contacto(); 
        int tamano = ListaContactos.size();
        //System.out.println("tamano "+tamano);
        
        
        posicion--;

        if(posicion<0){
           //posicion = 0;
           posicion = ListaContactos.size()-1; 
        }
        
        obcontacto.setPosicion(posicion);
        //System.out.println("seleccion "+posicion);
        if(posicion >= 0)
        {   
            //System.out.println("Dentro del si "+posicion);
            obcontacto = ListaContactos.get(posicion);
            txt_nombre.setText(obcontacto.getNombre());
            txt_apellido.setText(obcontacto.getApellidos());
            txt_telefono.setText(obcontacto.getTelefono());

        }
        /*else if(posicion < 0){
            //posicion++;
            posicion = tamano;
            System.out.println("Dentro del no "+posicion);
        }*/
        
         
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // btnSiguiente
        Contacto obcontacto = new Contacto(); 
        int tamano = ListaContactos.size();
        //System.out.println("tamano"+tamano);
        //i++;
        //mostrarContacto(ListaContactos.get(i));
        
        posicion++;
        
        if(posicion>=tamano){
           //posicion=tamano; 
           posicion = 0;
        }
        
        obcontacto.setPosicion(posicion);
        
        if(posicion < tamano)
        {   
            //System.out.println("Dentro del si "+posicion);
            obcontacto = ListaContactos.get(posicion);
            txt_nombre.setText(obcontacto.getNombre());
            txt_apellido.setText(obcontacto.getApellidos());
            txt_telefono.setText(obcontacto.getTelefono());

        }
        /*else if(posicion > tamano){
            //selecion--;
            posicion = -1;
            //System.out.println("Dentro del no "+posicion);
        }*/
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // btnModificar
        Contacto obcontacto = new Contacto();
        //obcontacto.getPosicion();       
        //System.out.println("tamano  "+posicion);
        
        obcontacto.setNombre(txt_nombre.getText()); 
        obcontacto.setApellidos(txt_apellido.getText());
        obcontacto.setTelefono(txt_telefono.getText());
        
        ListaContactos.set(posicion,obcontacto); //para modificar
        
        JOptionPane.showMessageDialog(rootPane, "Informacion modificada");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_telefono.setText("");
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void Q_PeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_PeekActionPerformed
        // Boton mostrar: Q_ppek()
       //mismo codigo de primer elemento
       mostrarContacto(ListaContactos.get(0));
       
    }//GEN-LAST:event_Q_PeekActionPerformed

    private void Q_Peek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_Peek2ActionPerformed
        // TODO add your handling code here:
        //mismo codigo que le boton de ultimoelemento
        mostrarContacto(ListaContactos.get(ListaContactos.size()-1));
    }//GEN-LAST:event_Q_Peek2ActionPerformed

    private void Q_Roll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_Roll1ActionPerformed
        // elimina primer elemento del array
        mostrarContacto(ListaContactos.get(0));
        ListaContactos.remove(0);
        
    }//GEN-LAST:event_Q_Roll1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // btnLimpiar
        Contacto obcontacto = new Contacto();
        ListaContactos.clear();
        txt_nombre.setText(obcontacto.getNombre());
        txt_apellido.setText(obcontacto.getApellidos());
        txt_telefono.setText(obcontacto.getTelefono());
        JOptionPane.showMessageDialog(rootPane, "Datos borrados");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void Q_RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_RollActionPerformed
        // elemina ultima posicion del array
        mostrarContacto(ListaContactos.get(ListaContactos.size()-1));
        ListaContactos.remove(ListaContactos.size()-1);
        
    }//GEN-LAST:event_Q_RollActionPerformed

    private void Btn_ArchivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ArchivarActionPerformed
        // boton rchivar
        ConexionArchivo conexion = new ConexionArchivo();
       try {
           conexion.GuardarLista(ListaContactos);
       } catch (IOException ex) {
           Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_Btn_ArchivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Archivar;
    private javax.swing.JButton Q_Peek;
    private javax.swing.JButton Q_Peek2;
    private javax.swing.JButton Q_Roll;
    private javax.swing.JButton Q_Roll1;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminarContacto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton guardarRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
